### ISSUE TITLE
Integration with NomadBay

### ISSUE THREAD

**Issue by njromano** [dm94/stiletto-web#2]
Hello Stilleto,

I am the dev for for NomadBay.org (testing alpha on https://nomadbay.azurewebsites.net), and I think we can work together on the trade API. 

I can probably enable CORS on the API and lookup authenticated users by their Discord ID. What do you think?

**Comment by njromano** [comment]
> I can probably enable CORS on the API and lookup authenticated users by their Discord ID.
That way you can request the data from a XHR request in javascript

**Comment by dm94** [comment]
> Hello Stilleto,
> 
> I am the dev for for NomadBay.org (testing alpha on https://nomadbay.azurewebsites.net), and I think we can work together on the trade API.
> 
> I can probably enable CORS on the API and lookup authenticated users by their Discord ID. What do you think?

You could see how to do it, I have also published the API and to see the list of trades you don't need authentication so the problem would be when adding new trades 

https://github.com/dm94/Stiletto-API

**Comment by njromano** [comment]
It will be pretty easy to add/update/delete with my API through REST methods (GET, POST, PUT, DELETE). I will figure it out next chance I get and post some usage docs.
